#--------------------------------------
# PARAMETERS
#--------------------------------------



#--------------------------------------
# Parameters for the timer
#--------------------------------------
timer.scheduler.autoCloseSessions=720
timer.cleanup.days=30
timer.scheduler.enabled=true
timer.scheduler.every.minutes=1
timer.timezone=Europe/Rome